// <auto-generated />
using API_consulta_Pessoa_Cadastrada.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_consulta_Pessoa_Cadastrada.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221007200454_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("testing_app.Model.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Bairro");

                    b.Property<string>("Cidade")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Cidade");

                    b.Property<string>("Logradouro")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Logradouro");

                    b.Property<string>("Numero")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Numero");

                    b.HasKey("Id")
                        .HasName("IdEndereco");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("testing_app.Model.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .HasColumnType("varchar(14)")
                        .HasColumnName("CPF");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NomePessoa");

                    b.Property<string>("RG")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("RG");

                    b.HasKey("Id")
                        .HasName("IdPessoa");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("testing_app.Model.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DDD")
                        .HasColumnType("int")
                        .HasColumnName("DDD");

                    b.Property<string>("Numero")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Numero");

                    b.Property<int>("TipoTelefone")
                        .HasColumnType("int")
                        .HasColumnName("TipoTelefone");

                    b.HasKey("Id")
                        .HasName("IdTelefone");

                    b.ToTable("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
