// <auto-generated />
using System;
using API_consulta_Pessoa_Cadastrada.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_consulta_Pessoa_Cadastrada.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("testing_app.Model.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Bairro");

                    b.Property<string>("Cidade")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Cidade");

                    b.Property<string>("Logradouro")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Logradouro");

                    b.Property<string>("Numero")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Numero");

                    b.Property<string>("UF")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("IdEndereco");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("testing_app.Model.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .HasColumnType("varchar(14)")
                        .HasColumnName("CPF");

                    b.Property<int?>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NomePessoa");

                    b.Property<string>("RG")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("RG");

                    b.Property<int?>("TelefoneId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("IdPessoa");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("TelefoneId");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("testing_app.Model.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DDD")
                        .HasColumnType("int")
                        .HasColumnName("DDD");

                    b.Property<string>("Numero")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Numero");

                    b.Property<int>("TipoTelefone")
                        .HasColumnType("int")
                        .HasColumnName("TipoTelefone");

                    b.HasKey("Id")
                        .HasName("IdTelefone");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("testing_app.Model.Pessoa", b =>
                {
                    b.HasOne("testing_app.Model.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId");

                    b.HasOne("testing_app.Model.Telefone", "Telefone")
                        .WithMany()
                        .HasForeignKey("TelefoneId");

                    b.Navigation("Endereco");

                    b.Navigation("Telefone");
                });
#pragma warning restore 612, 618
        }
    }
}
